### PR TITLE
add Bar orientation option

### PR DESCRIPTION
**Pull request by ghtmtt**
Just changed the plotly required name for bar orientation.

BTW: I copied the lines of the ``getTypeLayout`` function (just below the added code).. else the plot was not being rendered.

Issue: if horizontal, also the groups are re-computed.. that means the user has to invert the X and Y values. Should with add an if loop? I did not expect that behavior as user

### CODE REVIEW

**Comment by mdouchin** [comment]
About the inverted X and Y, this is weird. I think it is better to do the job for the user by automatically invert X and Y when needed.

**Comment by ghtmtt** [comment]
I also think we should do the job for the user.. some hints I can I do that? So I will add it to the same pull request and we are done.. 

In ``data_plot_trace`` the **x** and **y** axes are set. But the orientation properties are set in ``data_plot``..

**Comment by ghtmtt** [comment]
@mdouchin 

In the meanwhile I added **BoxPlot** (with all the options available) and **ScatterPlot** (not all the options available yest, but some of them are).

If you can review the code we can merge the pull request to master and continue the work ;)

**Comment by mdouchin** [comment]
Ok for me to merge. I have not tested it (I am away from my computer right now) but the modifications seem ok !

**Comment by ghtmtt** [comment]
I run some tests and It seems to work without any problems. I'll merge it and in case make some bug fixing afterwards

**Pull request merged**
